name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      example_input: Hello, World!
    secrets:
      EXAMPLE_SECRET: This is a scret